### Site Settings ###
title               : Jaemin Woo
description         : >-
                      Jaemin Woo
baseurl             : ""                    # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : wjm9932/wjm9932.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : wjm9932/wjm9932.github.io
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Jaemin Woo
  image             : https://www.sketchappsources.com/resources/source-image/coo-app-concept-subgaurav.jpg
  #behance           : your_username
# dribbble          : your_username
  email             : username@domain.com
  #facebook          : your_username
  github            : your_username
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

      


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
